### ISSUE TITLE
Add classification information

### ISSUE THREAD

**Issue by postmodern** [rubysec/ruby-advisory-db#17]
It would be nice if we imported some (maybe not all) of the classification information for advisories. This would provide the user with a more detailed breakdown of the advisory, than say CVSSv2 score.
## Example

```
classification:
  location: remote
  attack_type: input_manipulation
  impact: loss_of_integrity
```
