### ISSUE TITLE
Add references / related_urls to schema

### ISSUE THREAD

**Issue by phillmv** [rubysec/ruby-advisory-db#192]
As per #191 I'm very down to adding a bit of schema to all advisories for other sources of information. Like a `see_also` or a `references` or a `related_urls`. 

Right now my interpretation of a url is merely a canonical reference to the original advisory source.

The purpose of this ticket is to record this intent in the meantime; I suspect we may wish to revisit or formalize other bits of our schema.

**Comment by phillmv** [comment]
As got formalized in the test spec, we now accept:

```yaml
related:
  osvdb:
    - 12345
    - 12346
  cve:
    - 12347
    - 12348
   url:
     - http://example.com
     - http://example.com
```

This ticket remains open until the docs get updated.
