### ISSUE TITLE
No failed tests on unknown yaml structure

### ISSUE THREAD

**Issue by f3ndot** [rubysec/ruby-advisory-db#370]
We have some great validations for well-formed .yml files.

One way to take them a step further is to validate each key in the .yml file is known/expected and fail otherwise.

With such tests, we'd have caught 25eb46646c70315ee35d580d8be0af2e8db283a6 before it landed.

An oldie, but a goodie, this project seems to allow you to easily define YML schema and have tests for it's well-formed nature: http://www.kuwata-lab.com/kwalify/

**Comment by f3ndot** [comment]
Example of kwalify:

```
kwalify -l -f spec/advisory_schema.yml gems/**/*.yml
```

```yml
type: map
mapping:
 gem:
    type: str
    required: yes
 osvdb:
    type: number
    required: no
 url:
    type: str
    required: yes
 title:
    type: str
    required: yes
 date:
    type: str
    required: yes
 date:
    type: str
    required: yes
 patched_versions:
    type: seq
    required: no
    sequence:
      - type: str
```

and so on
